== Microservices Architecture

[ditaa]
----
         /------\           /------\
         | User |           | User |
         \------/           \------/
             |                  |
 +-----------|------------------|-----------+
 | OpenShift |                  |           |
 |           v                  v           |
 |  /------------------------------------\  |
 |  |           Load Balancer            |  |
 |  \------------------------------------/  |
 |          |                    |          |
 |  /---------------\    /---------------\  |
 |  |Pod            |    |Pod            |  |
 |  | /-----------\ |    | /-----------\ |  |
 |  | |    Web    | |    | |    Web    | |  |
 |  | \-----------/ |    | \-----------/ |  |
 |  |       |       |    |       |       |  |
 |  |       |       |    |       |       |  |
 |  |       v       |    |       v       |  |
 |  | /-----------\ |    | /-----------\ |  |
 |  | |    API    | |    | |    API    | |  |
 |  | \-----------/ |    | \-----------/ |  |
 |  |       |       |    |       |       |  |
 |  |       |       |    |       |       |  |
 |  |       v       |    |       v       |  |
 |  | /-----------\ |    | /-----------\ |  |
 |  | |   Cache   |<------>|   Cache   | |  |
 |  | \-----------/ |    | \-----------/ |  |
 |  \---------------/    \---------------/  |
 |          |                     |         |
 |          v                     v         |
 |  /------------------------------------\  |
 |  | /-----------\        /-----------\ |  |
 |  | | DataStore |--------| DataStore | |  |
 |  | \-----------/        \-----------/ |  |
 |  |             \        /             |  |
 |  |           /-----------\            |  |
 |  |  NoSQL    | DataStore |            |  |
 |  |           \-----------/            |  |
 |  \------------------------------------/  |
 +------------------------------------------+
----

Technical Stack from top to bottom:

- Spring Web MVC - Thymeleaf - https://www.thymeleaf.org
- Undertow - http://undertow.io
- Spring Boot - https://spring.io/projects/spring-boot
- Lombok Library - https://projectlombok.org/
- OpenJDK - http://openjdk.java.net/
- Infinispan Cache (Library Mode) - https://infinispan.org
- Datastax (Cassandra) - https://www.datastax.com
- OpenShift - https://www.openshift.com

The cache is configured for write-behind which persists data asynchronously to the actual Cassandra store.

See - http://infinispan.org/docs/9.0.x/user_guide/user_guide.html#cluster_cache_loader

=== Locally

===== (Optional) External API Mock
If you Don't have a https://www.themoviedb.org/documentation/api[themoviedb] API Key
you can run the mock servive recorded using https://github.com/flickr/yakbak[Yakbak]

[source,bash,options="wrap"]
----
$ cd popular-movie-store/yabak/movies
$ npm i
$ npm start
----

Else if you want to sign up see - https://www.themoviedb.org/documentation/api

[source,bash,options="wrap"]
----
echo -n '<your api key>' | base64
----

===== Datastax

If you want to run without a data store altogether - change `application.yml` to use

[source,bash,options="wrap"]
----
infinispan:
  embedded:
    config-xml: infinispan-no-datastore-moviestore.xml
[source,bash,options="wrap"]
----

To run a Single instance of Cassandra for testing - see https://academy.datastax.com/content/docker-tutorial

[source,bash,options="wrap"]
----
docker run -e DS_LICENSE=accept --name my-dse -p 9042:9042 -d datastax/dse-server
----

And change `application.yml` to use

[source,bash,options="wrap"]
----
infinispan:
  embedded:
    config-xml: infinispan-local-cassandra-moviestore.xml
[source,bash,options="wrap"]
----

The default setting is to run in OpenShift, with cassandra service listening on `cassandra.cassandra.svc[9042]`

[source,bash,options="wrap"]
----
infinispan:
  embedded:
    config-xml: infinispan-cassandra-moviestore.xml
[source,bash,options="wrap"]
----


===== Application

Run the application locally

[source,bash,options="wrap"]
----
export API_KEY=<base64 encoded moviedb api-key || empty if using mock>
export API_URL=<https://api.themoviedb.org || https://localhost:3000>
$ ./mvnw spring-boot:run
----



===== Test

Browse to

[source,bash,options="wrap"]
----
http://localhost:8080
----

Add some items to your cart.

Check casandra database has been written to:

[source,bash,options="wrap"]
----
$ docker exec -it my-dse bash
$ cqlsh
cqlsh> desc moviestore
cqlsh> select * from moviestore.movies;
cqlsh> select * from moviestore.sessions;
----

stop dse, see if cache still works

=== OpenShift

Deploy replicated cassandra in cassandra namesapce - see https://github.com/eformat/openshift-datastax

Make the namespace global so we can talk to it

[source,bash,options="wrap"]
----
$ oc adm pod-network make-projects-global cassandra
----

Deploy our movie store application in a separate namespace

[source,bash,options="wrap"]
----
$ oc new-project movie-store
$ mvn fabric8:deploy
----

===== Test

- Scale up application to 2 pods
- Add items to shopping basket
- Kill one pod - your web session is replicated, items in basket remain

Can see cached sessions in - http://popular-movie-store-movie-store.apps.<your-domain>/sessions

Scale down cassandra cache store. The in memory cache will still hold cached session replicas. Can then scale back up.

[source,bash,options="wrap"]
----
$ oc scale statefulset cassandra --replicas=0 -n cassandra
----

=== Cache settings and Application Behaviour

Using a shared, preloaded, write-behind cache

- Session Cache Settings description
http://infinispan.org/docs/9.2.x/user_guide/user_guide.html#configuration_3
