moviestore:
  apiEndpointUrl: "https://localhost:3000"
  apiKey: "${API_KEY}"
infinispan:
  embedded:
    config-xml: infinispan-cassandra-moviestore.xml
spring:
  thymeleaf:
    mode: HTML
    cache: false

